services:
    web:
        container_name: WebService
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - database
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        
    database:
        container_name: WebDatabase
        image: postgres:latest
        expose:
            - "5432"
        ports:
            - "5432:5432"
        env_file: 
            .env
        restart:
            unless-stopped
        volumes:
            - local_pg_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PORT: ${POSTGRES_PORT}

volumes:
    local_pg_data:
    static_volume:
    media_volume:

